-- DropForeignKey
ALTER TABLE "CHATHISTORY" DROP CONSTRAINT "CHATHISTORY_groupId_fkey";

-- AlterTable
ALTER TABLE "CHATHISTORY" ALTER COLUMN "groupId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "CHATHISTORY" ADD CONSTRAINT "CHATHISTORY_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "GROUP"("id") ON DELETE SET NULL ON UPDATE CASCADE;
