-- CreateTable
CREATE TABLE "HISTORY" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "HISTORY_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_HISTORYToUser" (
    "A" INTEGER NOT NULL,
    "B" INTEGER NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "HISTORY_id_key" ON "HISTORY"("id");

-- CreateIndex
CREATE UNIQUE INDEX "_HISTORYToUser_AB_unique" ON "_HISTORYToUser"("A", "B");

-- CreateIndex
CREATE INDEX "_HISTORYToUser_B_index" ON "_HISTORYToUser"("B");

-- AddForeignKey
ALTER TABLE "_HISTORYToUser" ADD CONSTRAINT "_HISTORYToUser_A_fkey" FOREIGN KEY ("A") REFERENCES "HISTORY"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_HISTORYToUser" ADD CONSTRAINT "_HISTORYToUser_B_fkey" FOREIGN KEY ("B") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
